development:
  clients:
    default:
      database: test_app_development
      hosts:
        - localhost:27017
production:
  clients:
    default:
      database: test_app_development
      hosts:
        - localhost:27017
        